# Generated by Django 4.0.2 on 2022-02-15 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_profile_csv"),
        ("spotify", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CSVFiles",
            new_name="CSVFile",
        ),
    ]
