# Generated by Django 4.0.2 on 2022-02-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_rename_csvfiles_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='name',
            field=models.CharField(default='Default', max_length=50),
        ),
    ]
