# Generated by Django 4.0.2 on 2022-02-22 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0003_alter_csvfile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="csvfile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
