# Generated by Django 4.0.2 on 2022-02-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_csvfile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='steak',
            field=models.CharField(default='Rare', max_length=50),
        ),
    ]
