# Generated by Django 4.0.2 on 2022-02-22 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_csvfile_steak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='steak',
        ),
    ]
